### ISSUE TITLE
crunchyroll-dl seems really slow

### ISSUE THREAD

**Issue by LeLachlan** [simplymemes/crunchyroll-dl#1]
Hi, I've been using crunchyroll-dl for a while now but today I noticed that it was unbearably slow. In fact, when it was done downloading the first episode of a show it crashed with this error:

``(node:23171) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/crunchyroll-dl/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/crunchyroll-dl/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/crunchyroll-dl/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:23171) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23171) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.``

I suspect it might have to do something with an issue that's been resolved over on the anime-dl project: https://github.com/Xonshiz/anime-dl/issues/74

Is this something that should be looked into or nah?

**Comment by viskotblood** [comment]
works fine for me just tested it,
i have a problem with choosing language i don't know what to put as a label .
and i can't login with normal account , should i subscribe?

**Comment by LeLachlan** [comment]
> works fine for me just tested it

Are you using Linux or Windows? While the script does kinda work it's unbearably slow for me.
Also, what's the point of logging in if you're using a normal account? crunchyroll-dl works just fine without an account.

**Comment by viskotblood** [comment]
tested on windows 7 & ubuntu 18 server  .. i don't know maybe you have unstable internet connection or a weak processor , the script does the downloading and the encoding at the same time using ffmpeg , every downloaded portion go through the ffmpeg encoder.. but ffmpeg is misconfigured  a 480p episode take more than 1GB disk space

**Comment by LeLachlan** [comment]
I have a pretty stable internet connection (100 up 100 down via ethernet on a fiber connection) and I wouldn't say my processor is weak (it's a Ryzen 5 1500X).

and yeah, it seems like crunchyroll-dl ignores the -q flag.

**Comment by viskotblood** [comment]
i got your error  output when i tried to download a country restricted episode even with the --unblocked  flag

**Comment by simplymemes** [comment]
@LeLachlan That error seems to be because Crunchyroll is down. In 1.1.0 (I just updated) it should tell you something like that rather than you having to guess.

@viskotblood It seems that Crunchyroll changed their way of sending the different files. Setting the resolution should properly work now, sorry about that. Please update.

Also, the languages you can set are as follows: (set to what is in "id")
```
[
  {
    "id": "enUS",
    "label": "English (US)"
  },
  {
    "id": "enGB",
    "label": "English (UK)"
  },
  {
    "id": "esLA",
    "label": "Español"
  },
  {
    "id": "esES",
    "label": "Español (España)"
  },
  {
    "id": "ptBR",
    "label": "Português (Brasil)"
  },
  {
    "id": "ptPT",
    "label": "Português (Portugal)"
  },
  {
    "id": "frFR",
    "label": "Français (France)"
  },
  {
    "id": "deDE",
    "label": "Deutsch"
  },
  {
    "id": "itIT",
    "label": "Italiano"
  },
  {
    "id": "ruRU",
    "label": "Русский"
  }
]
```
