### ISSUE TITLE
crunchyroll-dl Web

### ISSUE THREAD

**Issue by louanbastos** [simplymemes/crunchyroll-dl#11]
Do you want to try create a web app for crunchyroll-dl? i already created the frontend design: https://louanbastos.github.io/crunchyroll-dl-en/

email me: louanbastos61@gmail.com

**Comment by simplymemes** [comment]
Hmm, while this does seem possible, I'd rather not be involved with a website... I'd rather keep such tools locally, as I feel Crunchyroll would be less lenient with a website, compared to the multitude of tools available to download from their website on GitHub.

**Comment by louanbastos** [comment]
> Hmm, while this does seem possible, I'd rather not be involved with a website... I'd rather keep such tools locally, as I feel Crunchyroll would be less lenient with a website, compared to the multitude of tools available to download from their website on GitHub.

so just create for pc only, but with User Interface.

**Comment by simplymemes** [comment]
If you're planning on making this accessible over a website, you'd probably need a premium account fetching the links. I see there was another site on that page you linked - crunchydl - doesn't that use a premium account in the backend as well?

**Comment by louanbastos** [comment]
I have a premium login, and the site don't use, my website https://louanbastos.github.io/crunchyroll-dl-en/ is a just frontend
