### ISSUE TITLE
[Feature request] Can episode number be two fields instead of one for first nine episodes?

### ISSUE THREAD

**Issue by Abu3safeer** [simplymemes/crunchyroll-dl#14]
Hello everyone,

can you please make epsides from 1 to 9 be 01 to 09? 
must of seasonal animes are 12 episode, so having them 01 to 09 would be great.

Thank you.

**Comment by simplymemes** [comment]
While I didn't account for this in the creation of this feature, I can specify `-e 01-09` and it works fine. Specifying `-e 01,02,03,04,05,06,07,08,09` also works.

**Comment by Abu3safeer** [comment]
So if I want episodes name to be like:
Anime episode 1 => Anime episode 01
Anime episode 2 => Anime episode 02
Anime episode 3 => Anime episode 03
Anime episode 4 => Anime episode 04
I just have to specify  -e 01-09? 
but as far as I know that -e for limiting the download to specific episodes. 

I might not explained this clearly, I just want to change the number in the name, numbers with only one field does not prefix it with 0, that is what I try to say.

**Comment by Abu3safeer** [comment]
I think you might misunderstand me, 

Look at this
![image](https://user-images.githubusercontent.com/12091003/55726690-14228680-5a19-11e9-8cf8-003264355be4.png)


what I am trying to do is this
![image](https://user-images.githubusercontent.com/12091003/55726766-3caa8080-5a19-11e9-8508-8e176056d490.png)

did you get me?

**Comment by simplymemes** [comment]
@Abu3safeer Yeah, I understood your point... Still considering how to implement this, adding a tag for now
