### ISSUE TITLE
[Feature Request] Option to download an episode without subtitles

### ISSUE THREAD

**Issue by basuritashka** [simplymemes/crunchyroll-dl#18]
Title. 
I am from South America and I would like to start subbing some episodes that aren't on South America (Oregairu, for example). I can use the Unblocker to get the episodes but the subtitles are already on the .mp4, I would like to have the original .raw with their subtitles on the other hand.

Thanks.

**Comment by Abu3safeer** [comment]
That would be "Softsub" which is currently not supported by this app.

**Comment by simplymemes** [comment]
Sorry, there is no way to get subtitle-free videos with the Crunchyroll API, from what I could see.

**Comment by simplymemes** [comment]
Cancel that, I have added a new experimental feature in 1.3.5 to download without subtitles... `--language=none`

Please report any bugs you find! If this feature works well, I will look into softsub functionality :)

**Comment by basuritashka** [comment]
Amazing, I will be testing it :) going to update ASAP.

**Comment by Abu3safeer** [comment]
> I will look into softsub functionality :)

YAY 🎉

If this tool can download softsub and hardsub, then it will have no competitors. 
you could open an issue for testing the softsub functionality I would be glad to give some ideas about it.
