### ISSUE TITLE
[Bug] auto does not select higher quality when the higher is not in qualities array

### ISSUE THREAD

**Issue by Abu3safeer** [simplymemes/crunchyroll-dl#19]
Hello everyone

As you know there are several qualities provided by crunchyroll, they are here:
https://github.com/simplymemes/crunchyroll-dl/blob/bc5d7ef94b229cf647078f19b9a591490893ee5c/index.js#L34

But one show which is this:
https://www.crunchyroll.com/saki
have this quality:
1920x1072

as you can see it has 1072, which is lower than 1080, that made the application download 720p version.

So is there anyway to make this app use --quality auto to get the higher quality instead of looking for one of the qualities in the array?

**Comment by Abu3safeer** [comment]
By the way I has this issue with GTO also, there are several animes with different aspect ratio.

**Comment by Abu3safeer** [comment]
This is temporary fix for it until it can detect them by itself
https://github.com/simplymemes/crunchyroll-dl/pull/20

**Comment by simplymemes** [comment]
Fixed in 1.3.4

**Comment by Abu3safeer** [comment]
Thank you.
