### ISSUE TITLE
download always in 1080p

### ISSUE THREAD

**Issue by viskotblood** [simplymemes/crunchyroll-dl#2]
the script works fine but all downloads appear to be 1080p (downloaded file size: ~1.1GB )

**Comment by LeLachlan** [comment]
You'll have to set the -q flag, options are as follows:

best (usually 1080p)
1080p
720p
480p
240p

So there's nothing inherently wrong with the script since it's made to default to best.

**Comment by viskotblood** [comment]
thanks 
but why the encoded 480p video size is more than 1GB!
how can i modify ffmpeg options to reduce the file size?  vcodec or something like that

**Comment by LeLachlan** [comment]
As I said over on #1 it seems like crunchyroll-dl ignores the -q flag. It doesn't matter what you set it to since it'll still download the video in 1080p.

**Comment by simplymemes** [comment]
Been fixed in 1.1.0
