### ISSUE TITLE
Softsub Functionality

### ISSUE THREAD

**Issue by simplymemes** [simplymemes/crunchyroll-dl#22]
Hello all!

This is a discussion thread for a possible softsub functionality. This would require large portions to be rewritten, and is still under consideration for 2.0.0.

Please respond with any requests/ideas you have regarding this function :)

**Comment by Noctunus** [comment]
It would be great if multiple languages could be selected and integrated. So english is available for almost everything but other languages may be optionally available and I'ld like to choose the other ones to be integrated if available.

**Comment by Abu3safeer** [comment]
Great, I will write down some ideas:
1 - auto mux fonts, Crunchyroll offer fonts, so if this application can download them and mux them, then is should be great, if it cannot download them, then mux fonts presented in fonts folder in the same directory of the script, so I create a folder named fonts, this app detect the folder and mux all fonts inside it.
2 - ability to select languages to download, so I can select what I need and avoid what I don't want.
3 - multi connections, as you might know that download speed is not too great, so if it can download several episodes it ones that would make it even greater. 

when I have more ideas I will come back here.

**Comment by simplymemes** [comment]
Finally got around to pushing the first beta of 2.0.0, which has a basic implementation of soft sub functionality. 

You need mkvmerge now.

To activate it, at the end of a command put `-s soft` and it will prompt you for which subtitle languages to download, and download subs etc. to a temp folder before muxing. If you wish to skip, add `--subLangs` and place the subtitle languages, the same way as in `--language`. To download all, `--subLangs all`. There are no real other features yet, just trying to make sure my implementation works as I have not had the chance to do that much testing.

Thanks!

`npm i -g crunchyroll-dl@2.0.0-beta.1`

**Comment by basuritashka** [comment]
Working great.

**Comment by basuritashka** [comment]
@simplymemes I would like to update this that soft-sub functionality seems to be working but is not retrieving [V4+ Styles] correctly, exactly parameter "Name" is not working displaying a <blank> value.


![image](https://user-images.githubusercontent.com/33007491/61683584-fd602100-ace3-11e9-9ea4-8c25c5934006.png)

**Comment by basuritashka** [comment]
ScriptType parameter must be changed to: ScriptType: v4.00+ (line 42).

**Comment by simplymemes** [comment]
@basuritashka Thanks! Just pushed 2.0.0-beta.3 to address those changes.

**Comment by simplymemes** [comment]
Finally merged! Sorry for the super long delay!
