### ISSUE TITLE
ElectronJS APP

### ISSUE THREAD

**Issue by louanbastos** [simplymemes/crunchyroll-dl#24]
As one day I told you in: https://github.com/simplymemes/crunchyroll-dl/issues/11, you told me:
```Hmm, while this does seem possible, I'd rather not be involved with a website... I'd rather keep such tools locally, as I feel Crunchyroll would be less lenient with a website, compared to the multitude of tools available to download from their website on GitHub.```

So why you dont create a ElectronJS App for your app? if you want, i can try to create a beautiful UI

@Abu3safeer wants to do the same.!

**Comment by Abu3safeer** [comment]
I already have created a Windows app built with C# Here #15, The tool covers all crunchyroll-dl features, because I know developers won't bother to maintain a GUI while they want to focus on the core.
CLI applications are easier to maintain, this is why they use them.

**Comment by simplymemes** [comment]
Sorry, I feel like a CLI meets my needs quite fine. As @Abu3safeer said, there is the app in #15 made by him.

**Comment by louanbastos** [comment]
> Sorry, I feel like a CLI meets my needs quite fine. As @Abu3safeer said, there is the app in #15 made by him.

@simplymemes But in Electron JS can be created for multiple platforms, like, windows, mac, linux, and the program created by @Abu3safeer is just for windows.
