### ISSUE TITLE
Something went wrong when contacting Crunchyroll. They may be down... again

### ISSUE THREAD

**Issue by Andrew-Hartley** [simplymemes/crunchyroll-dl#25]
**It was working awesome last night be today I have been getting this message a ton. Crunchyroll is up. I love your work and want to find a solution to this problem. I have tried running it on 3 PC's on separate IP's many times and it only worked once on one of them this afternoon.**  Also if you want to help or anything I am working on adding a Path feature to set where it downloads and another feature so creates a folder and downloads the episodes to the folder with the anime title.

**Comment by simplymemes** [comment]
Would you mind running with `--debug` and posting the entire output?

**Comment by Andrew-Hartley** [comment]
Turns out Crunchyroll was just down for the hour
