### ISSUE TITLE
Exit Status always 1

### ISSUE THREAD

**Issue by GianGuido** [simplymemes/crunchyroll-dl#26]
Hey , first of all thanks for crunchyroll-dl , it's a life saver 👍 

I created a simple bash script to download new episodes weekly and i found out that
i cant check for a successful download because crunchyroll-dl always exit with 1, 
even if no errors occurred.

Here is the code , if anyone interested : 

```
#!/bin/sh
file=$(ls [0-9][0-9])
episode=$((file+1))
link=$(head -n 1 $file)
crunchyroll-dl --language xxXX --quality auto --download-all --episodes $episode --output ":name - :ep [:resolution]" --input $link
if [ $? -eq 0 ] 
then
    mv $file $episode
    exit $?
else    
    exit 1
fi
```

**Comment by simplymemes** [comment]
Fixed in 2.0.0
