### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Fileover** [simplymemes/crunchyroll-dl#28]
crunchyroll-dl --username XXXXX --password XXXXXX --subLangs all --quality 1080p --dont-autoselect-quality --vilos -s soft --input https://www.crunchyroll.com/pt-br/mob-psycho-100/episode-1-ripped-apart-someone-is-watching-787942

![image](https://user-images.githubusercontent.com/8651603/63097261-5b300380-bf46-11e9-9913-61b4e5dc6d2c.png)

**Comment by louanbastos** [comment]
Same with me

**Comment by simplymemes** [comment]
It appears that Crunchyroll has been using dash recently to introduce DRM for their Vilos (HTML) player, that broke things... Published 2.0.0-beta.4 to fix that!
