### ISSUE TITLE
The resolution specified was not found.

### ISSUE THREAD

**Issue by ramas-jpg** [simplymemes/crunchyroll-dl#3]
> `C:\Users\Administrador\AppData\Roaming\npm>crunchyroll-dl -i https://www.crunchyroll.com/my-hero-academia/episode-1-izuku-midoriya-origin-730707 -u xxxxxxxx -p xxxxxxx -q 1080p --unblocked -o ":epname [:resolution]
> i Attempting to login...
> i Successfully logged in!
> i Logged in with a premium account.
> i Successfully initiated USA Crunchyroll session
> i Attempting to fetch episode...
> i Downloading episode as "Izuku Midoriya Origin [1080p].mp4"
> ! The resolution specified was not found.
> i Done!
> i Logging out...`

Even specifying the quality, I get this error

Thank you for developing the tool.

**Comment by simplymemes** [comment]
Can you tell me which country you are in? I'll be pushing an update to include some debug logging later, but I'd like to get this fixed before pushing it out!

**Comment by ramas-jpg** [comment]
> Can you tell me which country you are in? I'll be pushing an update to include some debug logging later, but I'd like to get this fixed before pushing it out!

I'm from Brazil (ptBR)

**Comment by simplymemes** [comment]
Fixed in 1.1.1
