### ISSUE TITLE
Download only subtitle and video separately.

### ISSUE THREAD

**Issue by alphabet-works** [simplymemes/crunchyroll-dl#30]
I cannot select the language to none to download only the videos and subs separately in beta 2.0.0-2

**Comment by simplymemes** [comment]
This should be fixed in 2.0.0-beta.6.

Take a look at the examples for how to do this: https://github.com/simplymemes/crunchyroll-dl/tree/soft#examples

**Comment by alphabet-works** [comment]
it working great, thank
