### ISSUE TITLE
Not downloading videos (found temp fix)

### ISSUE THREAD

**Issue by WoaowMusic** [simplymemes/crunchyroll-dl#36]
I get the error
```
(node:15850) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'session_id' of undefined
    at main (/usr/local/lib/node_modules/crunchyroll-dl/index.js:163:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:15850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:15850) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I added my own session ID to `sessionId` around line 163 in index.js and it worked fine.

The workaround I found is to use the argument `--unblocked`.  This seemed to fix the issue I had.

Command that doesn't work:
`crunchyroll-dl -i <SHOW>`

Command that does work:
`crunchyroll-dl -i <SHOW> --unblocked`

This is most likely an issue not connecting to Crunchyroll correctly.  I'll look into it myself as well and see if I can fix it.

**Comment by simplymemes** [comment]
Crunchyroll removed support for the old device I was spoofing, I updated to the latest android version.
Fixed in 2.0.0-beta.7
