### ISSUE TITLE
mkvmerge not working

### ISSUE THREAD

**Issue by hydrangea-x1** [simplymemes/crunchyroll-dl#39]
When I put this in:
crunchyroll-dl -i https://www.crunchyroll.com/mob-psycho-100/episode-1-self-proclaimed-psychic-reigen-arataka-and-mob-715985 -s soft --language enUS

It works fine up until muxing, when I get the message that "mkvmerge is not recognised as an internal or external command, operable program or batch file"

Any help would be very much appreciated!

**Comment by noctarius** [comment]
Install mkvmerge and put it into your path variable: https://mkvtoolnix.download/downloads.html

**Comment by simplymemes** [comment]
Thanks for the heads up! Added it to the Readme as an optional requirement :)
Closing since this seems resolved.
