### ISSUE TITLE
something went wrong when contacting Crunchyroll.they may be down error.

### ISSUE THREAD

**Issue by viskotblood** [simplymemes/crunchyroll-dl#4]
i got this error but crunchyroll works fine! .. i think they changed  their api link

**Comment by viskotblood** [comment]
tested with another ip and it worked without any problem i think it was because  i reached my daily requests limit and  the api restricted the access for my ip address ,

**Comment by viskotblood** [comment]
can i unblock the session before or without  login in ? , i mean the first api call to start_session.0.json with a different ip 
 using unblocker to avoid this problem , or setting some axios global params , ..
please help me , and thank you so much for this tool

**Comment by simplymemes** [comment]
I have re-arranged code for this to work. 1.1.2
