### ISSUE TITLE
Where are the downloaded files?

### ISSUE THREAD

**Issue by theruleof4** [simplymemes/crunchyroll-dl#43]
I downloaded the files normally but I can't find where it was downloaded, even searching in Windows. The installation instructions do not mention where to save the files. Someone could help me?

**Comment by AlexIsOK** [comment]
The files are saved in the directory where you downloaded them.  If your command prompt was focused in `C:\Windows\System32` then it would download them there (if you were running this as admin), but it's more likely they are in your user folder (`C:\Users\<YOUR USERNAME>`).

You can use CD to change the directory you are in, for example: `cd C:\\Users\\<YOUR USERNAME>\\Videos` and save them there.

I haven't used this tool on Windows but I'm almost certain it'll save videos in the current directory on Windows as well as Linux.

**Comment by theruleof4** [comment]
Thanks. I founded it in C:\Windows\System32
