### ISSUE TITLE
Invalid Crunchyroll URL input

### ISSUE THREAD

**Issue by flashpc** [simplymemes/crunchyroll-dl#5]
It seems that CR has altered their address structure slightly, for example the oldest episode of Mr. Osomatsu's address is https://www.crunchyroll.com/en-gb/mr-osomatsu/episode-2-super-detergent-748871 which brings up the error, if you remove the "en-gb/" part it works fine on single episodes but not on the complete season

**Comment by simplymemes** [comment]
Fixed in 1.1.3.
