### ISSUE TITLE
(node:3481) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by ThatGiantSeth** [simplymemes/crunchyroll-dl#64]
When trying to download any episode and/or series, crunchyroll-dl crashes with this error:

crunchyroll-dl --quality 1080p --input https://www.crunchyroll.com/kaguya-sama-love-is-war

i crunchyroll-dl v2.0.1
i Attempting to fetch series...
(node:3601) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at main (/usr/local/lib/node_modules/crunchyroll-dl/index.js:588:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:3601) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3601) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I saw some similar issues posted here, but they were all different, sorry if this is still a duplicate.
I tried downloading just the Crunchyroll link (no quality options etc.), and also logging in with a username and password (successfully logged in), but still get the same error. It happens on any show I try, not just this one. The weird part is that it worked a few weeks ago with no problems, and I haven't changed anything since then.
Here's a screenshot in case I missed anything:
![Screenshot from 2020-11-12 14-26-44](https://user-images.githubusercontent.com/42821973/98986616-26b54980-24f3-11eb-95c5-992f12c04526.png)

**Comment by MarcoFleres** [comment]
This is caused by the regex that gets de series Id. A quick fix is replacing on index.js, line 586:
```
    const idDivRegex = /<div class="show-actions" group_id="(.*)"><\/div>/ // search for a div with an id
```
with:
```
const idDivRegex = /<div class="show-actions" group_id="(.*)"/ // search for a div with an id
```

...although this is also imperfect, as group_id is not necessarily next to the class. A more generic match would be better.

**Comment by ThatGiantSeth** [comment]
That fixed my issue, thanks so much! Kind of a novice at js so I had no idea what to do
