### ISSUE TITLE
Feature Request: Flags/Filter to auto-select collections

### ISSUE THREAD

**Issue by Noctunus** [simplymemes/crunchyroll-dl#9]
It would be more convenient to have flags + filters for auto-selecting collections and skipping the blocking dialog. This would in essence make the CLI-call a fire-and-forget execution where you don't have to wait for a dialog to come up and manually select the collections.

Some examples: 

1) Skip Single-Collection choice: https://www.crunchyroll.com/alice-zoroku
This series has only one collection available in US (the RU collection is not available there) in this case the whole dialog could be skipped as there is only one item to be selected anyway.
Same goes for all series which have only one collection.

2) Skip Multi-Collection choice without filter: https://www.crunchyroll.com/food-wars-shokugeki-no-soma
This series has three different seasons available and if I want to simply download all of them the selection could also be skipped.

3) Skip Multi-Collection choice with filter: https://www.crunchyroll.com/the-ancient-magus-bride
Here are many dubs available which I personally would filter out with general filters to sort out everything containing "Dub)" or "(RU)". This way only the ones are auto-selected not containing these expressions and an auto-skip/select would be possible.

**Comment by simplymemes** [comment]
Hey there.
In 1.3.0 I added a couple options to address this, as I was planning on adding something like this for a while.

`--ignore-dubs` will now attempt to ignore any dubs
`--episodes` will allow you to select episode ranges
`--download-all` will download all collections

The best part is, all of these can be used at the same time... For example:
```
crunchyroll-dl -i https://www.crunchyroll.com/fullmetal-alchemist-brotherhood --download-all --ignore-dubs --episodes 1-12,15-20
```
Would ignore the dubbed version of the show, choose the subbed season, and download episodes 1-12 and 15-20. 
I also tried to add a lot of feedback if something goes wrong.

Hope this helps!

**Comment by Noctunus** [comment]
Thank you and great work with this. I only have one minor issue with the "--episodes" parameter: If you only select one single episode it'll just drop out with an unhandle promise rejection. I'm aware that you can download single episodes with providing the direct link to it but without any proxy or session cookie magic in the browser you'll not be able to get that direct link for (out of your) region specific content. So at least for me it would be more convenient to be able to also select single episodes with the "--episodes" parameter.

**Comment by simplymemes** [comment]
@Noctunus 

Hmm, I see your point. I have fixed that bug in 1.3.1, and to hopefully help, I pushed a feature that I had in my private version - `--list`. It will list all the collections and episodes as a tree in your console.

**Comment by Abu3safeer** [comment]
Oh, you did a excellent job there.

**Comment by Noctunus** [comment]
@simplymemes the new list param is awesome - thanks for that.

The --ignore-dubs parameter is working most of the time but with series like https://www.crunchyroll.com/puella-magi-madoka-magica it'll also select the dubbed version as it's not following the "(LNG Dub)" naming but simply "(Dubbed)". Maybe you could extend the regex to also include the optional "bed" at the end?

**Comment by Noctunus** [comment]
Found another "minor" bug with the series: https://www.crunchyroll.com/squid-girl
The first collection contains some files with no episode number:
<pre>
└─ Squid Girl
   ├─ Squid Girl Season 1
   │  ├─ #(none) Squid Girl Preview #1
   │  ├─ #(none) Interview with Squid Girl (Hisako Kanemoto)
   │  ├─ #(none) Hat Making
   │  ├─ #(none) Squid Girl Preview #2
   │  ├─ #1 Who's up for a squid-vasion? / Hold on a squid, aren't you a compatriot? / Aren't I just the squiddiest?
   │  ├─ #2 Wait a squid, aren't you on my side? / Up for a squid-celebration? / Wanna play with this squid?
[...]
</pre>

Without providing the episode (-e)  parameter it'll drop out with:
<pre>
i Beginning to download "Squid Girl Season 1"
i Downloading episode (not set), "Squid Girl Preview #1", of "Squid Girl Season 1"
i Attempting to fetch episode...
! You may not have access to watch this episode
(node:4333) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at getEpisode (/usr/local/lib/node_modules/crunchyroll-dl/index.js:240:33)
    at < anonymous >
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

By simply selecting the episodes with -e 1-12 this error is avoided as the episodes are filtered out.

**Comment by simplymemes** [comment]
@Noctunus I quickly pushed 1.3.3 to address these two problems :)

**Comment by Abu3safeer** [comment]
Thank you very much.

**Comment by Noctunus** [comment]
@simplymemes
I'll close this ticket now as the suggested feature is implemented and tested so far. If anything else comes up I'll open a new ticket.

Thanks a lot!
